name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.2"
          - '3.0'
    container:
      image: ruby:${{ matrix.ruby }}
      env:
        BUNDLE_CLEAN: 'true'
        BUNDLE_DEPLOYMENT: 'true'
        BUNDLE_JOBS: 4
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-ruby${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-ruby${{ matrix.ruby }}-
      - run: bundle install
      - run: bundle exec rspec --format documentation
